### ISSUE TITLE
Cannot boot into installer

### ISSUE THREAD

**Issue by akhil-rana** [ssimondev/hackintosh#2]
I have downloaded the Ventura latest build and placed the provided EFI into my usb.

But I boot into the usb drive. I only see 2 options 
Reset NVRAM and Toggle SIP (disabled)

Screenshot is attached below
![IronHrt_20230327_235125_lmc_8 4-min](https://user-images.githubusercontent.com/36575628/228033623-ad764273-2d93-495c-8023-9e588a335783.jpg)

**Comment by akhil-rana** [comment]
I have the same hardware (probook 440g4) and I was able to install bigsur last year using my own config from my repo https://github.com/akhil-rana/HP-Probook-440G4-Big-Sur-Hackintosh

Maybe you can refer to it for getting your Bluetooth to work.

**Comment by sssssimon** [comment]
Hey, did you try resetting the NVRam if you already did try following this guide: https://www.youtube.com/watch?v=t_UBVy3zCAc&ab_channel=WillsRockson it really helped me a lot.

**Comment by akhil-rana** [comment]
Resetting NVRAM didn't help but I just got into the installer using this guide..
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#can-t-see-macos-partitions

Changed one or 2 options in config.plist and it seems to work. Thanks for the reply.

Now I'll try to get Bluetooth and audio jack to work.

**Comment by akhil-rana** [comment]
You have not mentioned in the readme if ethernet works or not. Have you tested that?

**Comment by sssssimon** [comment]
Sorry I will add that and yes it is working with Realtek Kext.

**Comment by sssssimon** [comment]
If you manage to get Bluetooth and audio jack to work please contact me.

**Comment by akhil-rana** [comment]
I got ventura installed with bluetooth working using this guide https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey-and-newer

But my system randomly reboots from time to time. Also it reboots whenever I click on the battery icon in the control center. Using wifi through heliport is also a headache so I think I'll probably try Monterey for now to see if it's more stable and wait unless ventura is better supported.

**Comment by sssssimon** [comment]
Hmm..... That's pretty weird. I remember i had some problems too. Try to change some bios settings if you want i can send you mine.

**Comment by akhil-rana** [comment]
I tried bios changes and even tried installing Monterey. 
But still when I click on battery icon the system freezes and reboots. 

It would be nice if you can share your bios settings. Maybe I'm missing something.

**Comment by akhil-rana** [comment]
So I fixed all my issues. I was using FakePCID kext which was not required and was causing all the issues.

Also I got the audio jack working. I just copied some entries from my old config file from bigsur where I had my custom PCI layout-id set in config.plist.

You can get audio jack working by modifying DeviceProperties->Add like shown in the screenshot below.
![image](https://user-images.githubusercontent.com/36575628/228306127-5a77fc40-b7c3-46c4-aefa-2874e2ecad70.png)


I'll create a github repo with my efi soon enough.

**Comment by sssssimon** [comment]
Thank you so much for the jack. I will add that to my repo as soon as possible

**Comment by akhil-rana** [comment]
I have updated my repo with the latest working EFIs for BigSur/Monterey/Ventura
Audio jack and bluetooth are also working in all of them.

https://github.com/akhil-rana/Hackintosh-HP-Probook-440-G4

I have credited you in the readme. Thanks for the help :)
